#!/usr/bin/env python3
"""Regenerate app/src/main/assets/schemes.txt from the iTerm2-Color-Schemes repository.

    git clone --depth 1 https://github.com/mbadolato/iTerm2-Color-Schemes /tmp/schemes
    tools/gen-schemes.py /tmp/schemes

The catalog is read from the repository's `ghostty/` directory: one file per
scheme, in Ghostty's `palette = N=#rrggbb` / `background = #rrggbb` form, which
is the simplest of the formats it publishes and the one the app also imports.

Nobody edits the asset by hand: three hundred palettes hand-maintained would
drift from upstream in a month. The output is one scheme per line,

    id<TAB>name<TAB>c0 c1 … c15<TAB>fg<TAB>bg<TAB>cursor<TAB>selection

with colors as six hex digits, so that the Kotlin side is a split per line and
an integer parse per color and nothing more. See Schemes.parseCatalog.
"""
import os
import re
import sys

# The app ships these six with hand-tuned palettes under stable ids
# (Schemes.BUILT_IN); the catalog's own copies would show up as doubles.
BUILT_IN_NAMES = {"one dark", "dracula", "gruvbox dark", "solarized dark", "nord", "light"}

HEX = re.compile(r"^#?([0-9a-fA-F]{6})$")


def color(value):
    m = HEX.match(value.strip())
    return m.group(1).lower() if m else None


def slug(name):
    s = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return s or "scheme"


def parse(path):
    palette = {}
    fields = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip()
            if key == "palette":
                idx, _, hexv = value.partition("=")
                c = color(hexv)
                if idx.strip().isdigit() and c:
                    palette[int(idx)] = c
            else:
                c = color(value)
                if c:
                    fields[key] = c
    if any(i not in palette for i in range(16)) or "foreground" not in fields or "background" not in fields:
        return None
    fg, bg = fields["foreground"], fields["background"]
    return {
        "ansi": [palette[i] for i in range(16)],
        "fg": fg,
        "bg": bg,
        "cursor": fields.get("cursor-color", fg),
        "selection": fields.get("selection-background", palette[8]),
    }


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    src = os.path.join(sys.argv[1], "ghostty")
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "app", "src", "main", "assets", "schemes.txt")
    os.makedirs(os.path.dirname(out), exist_ok=True)

    rows = []
    seen = set()
    skipped = []
    for name in sorted(os.listdir(src), key=str.lower):
        if name.lower() in BUILT_IN_NAMES:
            continue
        s = parse(os.path.join(src, name))
        if s is None:
            skipped.append(name)
            continue
        sid = slug(name)
        if sid in seen:
            skipped.append(f"{name} (id {sid} taken)")
            continue
        seen.add(sid)
        rows.append("\t".join([sid, name, " ".join(s["ansi"]), s["fg"], s["bg"], s["cursor"], s["selection"]]))

    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Generated by tools/gen-schemes.py from mbadolato/iTerm2-Color-Schemes (MIT). Do not edit.\n")
        f.write("\n".join(rows) + "\n")
    print(f"{len(rows)} schemes -> {os.path.relpath(out)} ({os.path.getsize(out)} bytes)")
    for s in skipped:
        print(f"skipped: {s}", file=sys.stderr)


if __name__ == "__main__":
    main()
